### ISSUE TITLE
Generating SDF causes an access violation if input stride is not same as the image width

### ISSUE THREAD

**Issue by suikki** [memononen/SDF#1]
_sdfBuildDistanceFieldNoAlloc()_ seems to access data outside the temp buffer if the stride value is larger than the input width.

https://github.com/memononen/SDF/blob/master/src/sdf.h#L213

^here In multiple places around row 213 the code is using _k_ for indexing temp array that includes the wrong stride (stride from the input data). I think it should just use _width_ when accessing the temp data.

Also, to get SDF to compile on mingw I had to change this: https://github.com/memononen/SDF/blob/master/src/sdf.h#L349

 to this:

```
    unsigned char* temp = (unsigned char*) malloc(width*height*sizeof(float)*3);
```

Anyway thanks for some great libs. Other than that it works nicely and I have my smooth outlined fonts now (btw I'm using fontstash too).

**Comment by memononen** [comment]
Thanks for spotting it! Both fixed now. My plan has been to put this into font stash. If you feel like it, a PR there would be awesome.

**Comment by suikki** [comment]
My font stash+SDF integration is kind of a quick hack, but maybe I could try to clean it up.

In the mean time I ran into another issue. I'll create a new issue for it.
