### ISSUE TITLE
Distance field is not generated properly for sharp edges in the source image.

### ISSUE THREAD

**Issue by suikki** [memononen/SDF#2]
I ran into some other issue with SDF still. I'm not sure if it's a fundamental issue with how the algorithm works (as I have no clue how it works) or if it's some other kind of error that would be easily fixed. The description does say it is assumed that there is one pixel width of anti-aliasing but I understood that hard edges should still work.

Some of my glyphs contain sections where the pixels align perfectly with the vector data so that even with anti-aliasing the edge pixels change straight from 0 opacity to 255.

In these regions the distance field is not generated at all. Example glyph showing the issue:

![sdf_issue](https://cloud.githubusercontent.com/assets/4216491/4512973/9bb3113c-4b46-11e4-9470-38e43b4ee035.png)

I did a quick & dumb fix to my code where I detect fully opaque pixels that have fully transparent neighbors (above,left,right,below) before I give the pixel data to SDF. If such a pixel is found I just set it's value to 254 instead of 255.

It seems to work but I it's not really a proper fix.

**Comment by memononen** [comment]
Looks like that the check for >0 && <255 skips those edges:
https://github.com/memononen/SDF/blob/master/src/sdf.h#L198

If that check is removed the quality of the distance field is much much worse. I have to check if I need to make special case for that.
